In [5]:
import pandas as pd

In [6]:
meta_df = pd.read_csv("main_metadata2024.csv")
meta_df

C:\Users\PYTHON\AppData\Local\Temp\ipykernel_26348\3991956641.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  meta_df = pd.read_csv("main_metadata2024.csv")

,version,match_id,leagueid,start_date_time,duration,cluster,replay_salt,radiant_win,pre_game_duration,match_seq_num,...,dire_captain,patch,region,throw,loss,comeback,stomp,replay_url,series_id,series_type
0,21.0,7515635423,15660,2024-01-01 00:24:16,1926,274,1.867420e+09,True,90,6326215446,...,1.773383e+08,54,3.0,571.0,8188.0,NaN,NaN,http://replay274.valve.net/570/7515635423_1867...,NaN,NaN
1,21.0,7515660161,15660,2024-01-01 01:06:17,1731,273,5.376493e+08,False,90,6326236598,...,2.942451e+08,54,3.0,NaN,NaN,3347.0,22431.0,http://replay273.valve.net/570/7515660161_5376...,NaN,NaN
2,21.0,7515737711,15819,2024-01-01 03:11:08,2056,271,1.091207e+09,True,90,6326314613,...,1.459382e+09,54,3.0,348.0,7541.0,NaN,NaN,http://replay271.valve.net/570/7515737711_1091...,838321.0,1.0
3,21.0,7515745579,15716,2024-01-01 03:23:40,2221,272,1.909215e+09,True,90,6326319934,...,9.486598e+08,54,3.0,2602.0,11185.0,NaN,NaN,http://replay272.valve.net/570/7515745579_1909...,838323.0,1.0
4,21.0,7515769503,16011,2024-01-01 04:00:28,1998,153,1.445754e+09,False,90,6326342223,...,1.542238e+08,54,5.0,NaN,NaN,1361.0,29785.0,http://replay153.valve.net/570/7515769503_1445...,838324.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30007,21.0,8107301381,17163,2024-12-31 20:05:27,1654,274,9.681039e+08,False,90,6817152200,...,4.605762e+08,56,3.0,NaN,NaN,1703.0,5789.0,http://replay274.valve.net/570/8107301381_9681...,938488.0,1.0
30008,21.0,8107336076,17163,2024-12-31 20:47:57,2029,274,7.437311e+08,True,90,6817179354,...,6.418801e+07,56,3.0,1096.0,9678.0,NaN,NaN,http://replay274.valve.net/570/8107336076_7437...,938488.0,1.0
30009,21.0,8107371640,17163,2024-12-31 21:38:22,1820,274,2.392427e+07,True,90,6817217409,...,1.922376e+08,56,3.0,7193.0,8268.0,NaN,NaN,http://replay274.valve.net/570/8107371640_2392...,938491.0,1.0
30010,21.0,8107417584,17163,2024-12-31 22:36:25,1861,274,1.059218e+09,False,90,6817242493,...,3.426673e+08,56,3.0,NaN,NaN,2010.0,15940.0,http://replay274.valve.net/570/8107417584_1059...,938491.0,1.0
30011,21.0,8107454803,17163,2024-12-31 23:26:12,1796,273,1.936275e+09,False,90,6817272708,...,3.158503e+08,56,3.0,NaN,NaN,7078.0,11807.0,http://replay273.valve.net/570/8107454803_1936...,938494.0,1.0

In [7]:
meta_df = meta_df.filter(items=['match_id', 'duration', 'radiant_win'])
meta_df

         match_id  duration radiant_win
0      7515635423      1926        True
1      7515660161      1731       False
2      7515737711      2056        True
3      7515745579      2221        True
4      7515769503      1998       False
...           ...       ...         ...
30007  8107301381      1654       False
30008  8107336076      2029        True
30009  8107371640      1820        True
30010  8107417584      1861       False
30011  8107454803      1796       False

[30012 rows x 3 columns]

In [8]:
draft_df = pd.read_csv("picks_bans.csv")
draft_df

        is_pick  hero_id  team  order    match_id  leagueid
0         False        8     0      0  7515635423     15660
1         False       50     1      1  7515635423     15660
2         False      119     1      2  7515635423     15660
3         False        7     0      3  7515635423     15660
4         False       51     1      4  7515635423     15660
...         ...      ...   ...    ...         ...       ...
710382    False       12     0     19  8107454803     17163
710383    False       89     0     20  8107454803     17163
710384    False      126     1     21  8107454803     17163
710385     True       44     1     22  8107454803     17163
710386     True        8     0     23  8107454803     17163

[710387 rows x 6 columns]

In [9]:
draft_df = draft_df[draft_df.is_pick == True]
draft_df

        is_pick  hero_id  team  order    match_id  leagueid
7          True       83     0      7  7515635423     15660
8          True       71     1      8  7515635423     15660
12         True       26     1     12  7515635423     15660
13         True       79     0     13  7515635423     15660
14         True       11     0     14  7515635423     15660
...         ...      ...   ...    ...         ...       ...
710378     True       81     0     15  8107454803     17163
710379     True        7     0     16  8107454803     17163
710380     True       29     1     17  8107454803     17163
710385     True       44     1     22  8107454803     17163
710386     True        8     0     23  8107454803     17163

[297107 rows x 6 columns]

In [10]:
draft_df = draft_df.filter(items=['match_id', 'team', 'hero_id']).reset_index(drop=True)

In [11]:
draft_df

          match_id  team  hero_id
0       7515635423     0       83
1       7515635423     1       71
2       7515635423     1       26
3       7515635423     0       79
4       7515635423     0       11
...            ...   ...      ...
297102  8107454803     0       81
297103  8107454803     0        7
297104  8107454803     1       29
297105  8107454803     1       44
297106  8107454803     0        8

[297107 rows x 3 columns]

In [12]:
import pandas as pd
meta_df = pd.read_csv("main_metadata2024.csv", low_memory=False)
meta_df = meta_df.filter(items=['match_id', 'duration', 'radiant_win'])
draft_df = pd.read_csv("picks_bans.csv", low_memory=False)

if 'is_pick' in draft_df.columns: 
    draft_df = draft_df[draft_df['is_pick'] == True]
elif 'pick' in draft_df.columns:
    draft_df = draft_df[draft_df['pick'] == True]
else:
    print("Столбцы в draft_df:", draft_df.columns.tolist())
    raise ValueError("Столбец с информацией о пиках не найден (проверьте название)")

draft_df = draft_df.filter(items=['match_id', 'team', 'hero_id']).reset_index(drop=True)

for i in range(len(meta_df)):
    match_picks = draft_df[draft_df['match_id'] == meta_df.iloc[i]['match_id']]
    dire = match_picks[match_picks['team'] == 1]
    radiant = match_picks[match_picks['team'] == 0]
    
    for j in range(len(dire)):
        meta_df.loc[i, f"dire_hero_{j+1}"] = dire.iloc[j]['hero_id']
    for j in range(len(radiant)):
        meta_df.loc[i, f"radiant_hero_{j+1}"] = radiant.iloc[j]['hero_id']

if len(meta_df) > 0:
    first_match_picks = draft_df[draft_df['match_id'] == meta_df.iloc[0]['match_id']]  
    dire_heroes = first_match_picks[first_match_picks['team'] == 1]
    
    print("Герои Dire в первом матче:")
    for i in range(min(5, len(dire_heroes))):  
        print(f"Слот {i+1}: {dire_heroes.iloc[i]['hero_id']}")

Герои Dire в первом матче:
Слот 1: 71
Слот 2: 26
Слот 3: 87
Слот 4: 48
Слот 5: 39

In [13]:
meta_df

,match_id,duration,radiant_win,dire_hero_1,dire_hero_2,dire_hero_3,dire_hero_4,dire_hero_5,radiant_hero_1,radiant_hero_2,radiant_hero_3,radiant_hero_4,radiant_hero_5,dire_hero_6,dire_hero_7,radiant_hero_6,radiant_hero_7,radiant_hero_8
0,7515635423,1926,True,71.0,26.0,87.0,48.0,39.0,83.0,79.0,11.0,10.0,107.0,NaN,NaN,NaN,NaN,NaN
1,7515660161,1731,False,95.0,107.0,123.0,68.0,17.0,119.0,50.0,98.0,11.0,67.0,NaN,NaN,NaN,NaN,NaN
2,7515737711,2056,True,137.0,112.0,103.0,16.0,35.0,27.0,98.0,45.0,94.0,129.0,NaN,NaN,NaN,NaN,NaN
3,7515745579,2221,True,27.0,100.0,33.0,25.0,76.0,5.0,26.0,14.0,18.0,22.0,NaN,NaN,NaN,NaN,NaN
4,7515769503,1998,False,102.0,121.0,85.0,10.0,39.0,71.0,30.0,86.0,17.0,12.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30007,8107301381,1654,False,36.0,11.0,22.0,26.0,54.0,68.0,62.0,84.0,114.0,1.0,NaN,NaN,NaN,NaN,NaN
30008,8107336076,2029,True,64.0,51.0,84.0,114.0,109.0,35.0,22.0,36.0,25.0,49.0,NaN,NaN,NaN,NaN,NaN
30009,8107371640,1820,True,11.0,48.0,2.0,101.0,30.0,85.0,86.0,46.0,104.0,39.0,NaN,NaN,NaN,NaN,NaN
30010,8107417584,1861,False,86.0,31.0,104.0,39.0,42.0,11.0,48.0,2.0,101.0,87.0,NaN,NaN,NaN,NaN,NaN
30011,8107454803,1796,False,11.0,22.0,119.0,29.0,44.0,79.0,138.0,81.0,7.0,8.0,NaN,NaN,NaN,NaN,NaN

In [14]:
meta_df.columns

Index(['match_id', 'duration', 'radiant_win', 'dire_hero_1', 'dire_hero_2',
       'dire_hero_3', 'dire_hero_4', 'dire_hero_5', 'radiant_hero_1',
       'radiant_hero_2', 'radiant_hero_3', 'radiant_hero_4', 'radiant_hero_5',
       'dire_hero_6', 'dire_hero_7', 'radiant_hero_6', 'radiant_hero_7',
       'radiant_hero_8'],
      dtype='object')

In [15]:
meta_df = meta_df.drop(columns=["dire_hero_6",	"dire_hero_7"])

In [16]:
meta_df

,match_id,duration,radiant_win,dire_hero_1,dire_hero_2,dire_hero_3,dire_hero_4,dire_hero_5,radiant_hero_1,radiant_hero_2,radiant_hero_3,radiant_hero_4,radiant_hero_5,radiant_hero_6,radiant_hero_7,radiant_hero_8
0,7515635423,1926,True,71.0,26.0,87.0,48.0,39.0,83.0,79.0,11.0,10.0,107.0,NaN,NaN,NaN
1,7515660161,1731,False,95.0,107.0,123.0,68.0,17.0,119.0,50.0,98.0,11.0,67.0,NaN,NaN,NaN
2,7515737711,2056,True,137.0,112.0,103.0,16.0,35.0,27.0,98.0,45.0,94.0,129.0,NaN,NaN,NaN
3,7515745579,2221,True,27.0,100.0,33.0,25.0,76.0,5.0,26.0,14.0,18.0,22.0,NaN,NaN,NaN
4,7515769503,1998,False,102.0,121.0,85.0,10.0,39.0,71.0,30.0,86.0,17.0,12.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30007,8107301381,1654,False,36.0,11.0,22.0,26.0,54.0,68.0,62.0,84.0,114.0,1.0,NaN,NaN,NaN
30008,8107336076,2029,True,64.0,51.0,84.0,114.0,109.0,35.0,22.0,36.0,25.0,49.0,NaN,NaN,NaN
30009,8107371640,1820,True,11.0,48.0,2.0,101.0,30.0,85.0,86.0,46.0,104.0,39.0,NaN,NaN,NaN
30010,8107417584,1861,False,86.0,31.0,104.0,39.0,42.0,11.0,48.0,2.0,101.0,87.0,NaN,NaN,NaN
30011,8107454803,1796,False,11.0,22.0,119.0,29.0,44.0,79.0,138.0,81.0,7.0,8.0,NaN,NaN,NaN

In [17]:
meta_df = meta_df.drop(columns=["radiant_hero_7", "radiant_hero_8","radiant_hero_6"])

In [18]:
meta_df

,match_id,duration,radiant_win,dire_hero_1,dire_hero_2,dire_hero_3,dire_hero_4,dire_hero_5,radiant_hero_1,radiant_hero_2,radiant_hero_3,radiant_hero_4,radiant_hero_5
0,7515635423,1926,True,71.0,26.0,87.0,48.0,39.0,83.0,79.0,11.0,10.0,107.0
1,7515660161,1731,False,95.0,107.0,123.0,68.0,17.0,119.0,50.0,98.0,11.0,67.0
2,7515737711,2056,True,137.0,112.0,103.0,16.0,35.0,27.0,98.0,45.0,94.0,129.0
3,7515745579,2221,True,27.0,100.0,33.0,25.0,76.0,5.0,26.0,14.0,18.0,22.0
4,7515769503,1998,False,102.0,121.0,85.0,10.0,39.0,71.0,30.0,86.0,17.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30007,8107301381,1654,False,36.0,11.0,22.0,26.0,54.0,68.0,62.0,84.0,114.0,1.0
30008,8107336076,2029,True,64.0,51.0,84.0,114.0,109.0,35.0,22.0,36.0,25.0,49.0
30009,8107371640,1820,True,11.0,48.0,2.0,101.0,30.0,85.0,86.0,46.0,104.0,39.0
30010,8107417584,1861,False,86.0,31.0,104.0,39.0,42.0,11.0,48.0,2.0,101.0,87.0
30011,8107454803,1796,False,11.0,22.0,119.0,29.0,44.0,79.0,138.0,81.0,7.0,8.0

In [19]:
meta_df.to_csv("data.csv")

In [20]:
def reccomend(your_team_picks, enemy_team_picks):
    game_df = meta_df[(all(hero in [meta_df.dire_hero_1, meta_df.dire_hero_2, meta_df.dire_hero_3, meta_df.dire_hero_4, meta_df.dire_hero_5] for hero in your_team_picks) & 
                       all(hero in [meta_df.radiant_hero_1, meta_df.radiant_hero_2, meta_df.radiant_hero_3, meta_df.radiant_hero_4, meta_df.radiant_hero_5] for hero in enemy_team_picks_team_picks) &
                        meta_df.radiant_win == False) |
                       (all(hero in [meta_df.dire_hero_1, meta_df.dire_hero_2, meta_df.dire_hero_3, meta_df.dire_hero_4, meta_df.dire_hero_5] for hero in enemy_team_picks) & 
                       all(hero in [meta_df.radiant_hero_1, meta_df.radiant_hero_2, meta_df.radiant_hero_3, meta_df.radiant_hero_4, meta_df.radiant_hero_5] for hero in your_team_picks_team_picks) &
                        meta_df.radiant_win == True)]
    return game_df

In [21]:
meta_df.dire_hero_5.value_counts()

dire_hero_5
48.0     1107
106.0     917
17.0      737
13.0      684
39.0      680
         ...
83.0       29
68.0       28
30.0       26
37.0       24
66.0       21
Name: count, Length: 124, dtype: int64

In [22]:
filter_matches(meta_df,[83.0], [71.0])

NameError: name 'filter_matches' is not defined

In [43]:
import pandas as pd

def filter_matches(df, your_team_picks, enemy_team_picks):
    """
    Фильтрует матчи, где одна команда содержит ВСЕХ героев из your_team_picks,
    а противоположная - ВСЕХ героев из enemy_team_picks
    
    Параметры:
    df (DataFrame): Исходные данные матчей
    your_team_picks (list): ID героев вашей команды (1-5 элементов)
    enemy_team_picks (list): ID героев противника (1-5 элементов)
    
    Возвращает:
    DataFrame с отфильтрованными матчами
    """
    # Преобразуем списки в множества
    your_set = set(your_team_picks)
    enemy_set = set(enemy_team_picks)
    
    # Функция проверки полного вхождения героев
    def contains_all_heroes(row, team_side, heroes):
        team_heroes = {row[f'{team_side}_hero_{i}'] for i in range(1, 6)}
        return heroes.issubset(team_heroes)
    
    # Проверяем два возможных сценария
    mask_scenario1 = df.apply(
        lambda x: contains_all_heroes(x, 'radiant', your_set) 
        and contains_all_heroes(x, 'dire', enemy_set),
        axis=1
    )
    
    mask_scenario2 = df.apply(
        lambda x: contains_all_heroes(x, 'dire', your_set) 
        and contains_all_heroes(x, 'radiant', enemy_set),
        axis=1
    )
    
    # Комбинируем маски
    result_df = df[mask_scenario1 | mask_scenario2]
    
    return result_df.reset_index(drop=True)

In [24]:
meta_df.columns

Index(['match_id', 'duration', 'radiant_win', 'dire_hero_1', 'dire_hero_2',
       'dire_hero_3', 'dire_hero_4', 'dire_hero_5', 'radiant_hero_1',
       'radiant_hero_2', 'radiant_hero_3', 'radiant_hero_4', 'radiant_hero_5'],
      dtype='object')

In [36]:
train_df = pd.read_csv("main_metadata2025.csv")
train_df

,version,match_id,leagueid,start_date_time,duration,series_id,series_type,cluster,replay_salt,radiant_win,...,dire_captain,patch,region,comeback,stomp,throw,loss,replay_url,radiant_logo,dire_logo
0,22.0,8237333738,17874,2025-04-01 00:34:17,1686,963272.0,1.0,122,2.007149e+09,False,...,3.191241e+08,57,2.0,7162.0,12671.0,NaN,NaN,http://replay122.valve.net/570/8237333738_2007...,6.259405e+16,4.215369e+18
1,22.0,8237333903,17211,2025-04-01 00:36:05,1804,963273.0,1.0,271,1.362944e+09,True,...,3.426673e+08,57,3.0,NaN,NaN,4262.0,9409.0,http://replay271.valve.net/570/8237333903_1362...,2.446097e+18,1.839182e+18
2,22.0,8237372778,17211,2025-04-01 01:52:32,1615,963293.0,1.0,272,8.121268e+08,True,...,1.261304e+08,57,3.0,NaN,NaN,658.0,16883.0,http://replay272.valve.net/570/8237372778_8121...,2.412313e+18,2.431454e+18
3,22.0,8237391929,17211,2025-04-01 02:28:15,2162,963293.0,1.0,271,1.798190e+08,False,...,1.673878e+09,57,3.0,6193.0,12011.0,NaN,NaN,http://replay271.valve.net/570/8237391929_1798...,2.431454e+18,2.412313e+18
4,22.0,8237577610,17874,2025-04-01 08:02:57,2497,963326.0,1.0,153,1.667491e+09,True,...,1.964000e+08,57,5.0,NaN,NaN,4076.0,17110.0,http://replay153.valve.net/570/8237577610_1667...,3.894373e+16,3.894998e+16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637,22.0,8244979564,17211,2025-04-06 21:22:16,1855,965205.0,1.0,272,6.045124e+08,False,...,2.006690e+08,57,3.0,2214.0,6256.0,NaN,NaN,http://replay272.valve.net/570/8244979564_6045...,2.041868e+18,2.446097e+18
638,22.0,8245009176,17211,2025-04-06 22:03:24,1690,965205.0,1.0,271,1.201586e+09,True,...,2.794862e+08,57,3.0,NaN,NaN,5320.0,11084.0,http://replay271.valve.net/570/8245009176_1201...,2.446097e+18,2.041868e+18
639,22.0,8245032799,17211,2025-04-06 22:42:18,1884,965228.0,1.0,271,6.928721e+08,True,...,3.512789e+07,57,3.0,NaN,NaN,506.0,19288.0,http://replay271.valve.net/570/8245032799_6928...,2.460727e+18,1.990058e+18
640,22.0,8245056252,17211,2025-04-06 23:25:41,2076,965228.0,1.0,274,1.608829e+08,True,...,1.799862e+08,57,3.0,NaN,NaN,7851.0,11767.0,http://replay274.valve.net/570/8245056252_1608...,1.990058e+18,2.460727e+18
641,22.0,8245079060,17211,2025-04-07 00:13:25,1723,965228.0,1.0,274,1.739768e+09,True,...,3.707361e+08,57,3.0,NaN,NaN,4011.0,13094.0,http://replay274.valve.net/570/8245079060_1739...,2.460727e+18,1.990058e+18

In [25]:
meta_df1 = pd.read_csv("main_metadata 1.csv")
meta_df1

,version,match_id,leagueid,start_date_time,duration,cluster,replay_salt,radiant_win,pre_game_duration,match_seq_num,...,dire_captain,patch,region,throw,loss,comeback,stomp,replay_url,series_id,series_type
0,21.0,8107483721,17163,2025-01-01 00:09:05,2059,274,1.271852e+09,False,90,6817296376,...,1.884087e+08,56,3.0,NaN,NaN,52.0,9324.0,http://replay274.valve.net/570/8107483721_1271...,938494.0,1.0
1,21.0,8107511870,17163,2025-01-01 00:53:00,1856,272,1.100233e+09,False,90,6817319003,...,3.076244e+08,56,3.0,NaN,NaN,6220.0,15460.0,http://replay272.valve.net/570/8107511870_1100...,938494.0,1.0
2,21.0,8107808159,17565,2025-01-01 08:01:42,2242,145,1.700596e+09,False,90,6817550308,...,4.024864e+08,56,19.0,NaN,NaN,-192.0,8961.0,http://replay145.valve.net/570/8107808159_1700...,938509.0,1.0
3,21.0,8107860205,17565,2025-01-01 08:54:22,1608,145,1.469288e+09,True,90,6817582339,...,4.024864e+08,56,19.0,5301.0,3160.0,NaN,NaN,http://replay145.valve.net/570/8107860205_1469...,938509.0,1.0
4,21.0,8107907898,17565,2025-01-01 09:41:43,2545,144,1.153657e+09,False,90,6817630886,...,4.024864e+08,56,19.0,NaN,NaN,5498.0,6479.0,http://replay144.valve.net/570/8107907898_1153...,938509.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,21.0,8154009506,17163,2025-01-31 21:27:01,2012,271,1.825698e+09,True,90,6854435259,...,8.445865e+08,56,3.0,140.0,14127.0,NaN,NaN,http://replay271.valve.net/570/8154009506_1825...,945389.0,1.0
2962,21.0,8154048015,17366,2025-01-31 22:04:26,1722,185,3.413918e+08,False,90,6854467285,...,1.126606e+09,56,8.0,NaN,NaN,-100.0,19675.0,http://replay185.valve.net/570/8154048015_3413...,945386.0,1.0
2963,21.0,8154055327,17163,2025-01-31 22:13:34,1876,272,1.542196e+09,True,90,6854469406,...,3.426673e+08,56,3.0,5126.0,11885.0,NaN,NaN,http://replay272.valve.net/570/8154055327_1542...,945389.0,1.0
2964,21.0,8154090172,17163,2025-01-31 22:54:13,1607,274,1.111874e+09,True,90,6854498933,...,3.158503e+08,56,3.0,2161.0,11472.0,NaN,NaN,http://replay274.valve.net/570/8154090172_1111...,945389.0,1.0
2965,21.0,8154121010,17163,2025-01-31 23:40:58,2286,272,1.134643e+09,True,90,6854530252,...,9.550197e+07,56,3.0,1971.0,11146.0,NaN,NaN,http://replay272.valve.net/570/8154121010_1134...,945401.0,1.0

In [26]:
meta_df2 = pd.read_csv("main_metadata 2.csv")
meta_df2

,version,match_id,leagueid,start_date_time,duration,series_id,series_type,cluster,replay_salt,radiant_win,...,dire_captain,patch,region,comeback,stomp,throw,loss,replay_url,radiant_logo,dire_logo
0,21.0,8154152426,17163,2025-02-01 00:28:53,1792,945401.0,1.0,274,6.151913e+08,False,...,2.794862e+08,56,3.0,1643.0,9993.0,NaN,NaN,http://replay274.valve.net/570/8154152426_6151...,2.446097e+18,2.041868e+18
1,21.0,8154175223,17163,2025-02-01 01:09:18,1974,945417.0,1.0,271,8.349152e+07,False,...,2.343823e+08,56,3.0,6.0,21626.0,NaN,NaN,http://replay271.valve.net/570/8154175223_8349...,2.431454e+18,1.914618e+18
2,21.0,8154200165,17163,2025-02-01 01:52:56,1570,945417.0,1.0,274,1.633427e+09,False,...,1.202314e+08,56,3.0,769.0,15961.0,NaN,NaN,http://replay274.valve.net/570/8154200165_1633...,1.914618e+18,2.431454e+18
3,21.0,8154222929,17163,2025-02-01 02:31:11,2109,945417.0,1.0,273,2.423543e+08,True,...,4.371359e+08,56,3.0,NaN,NaN,5092.0,8962.0,http://replay273.valve.net/570/8154222929_2423...,2.431454e+18,1.914618e+18
4,21.0,8154288597,17233,2025-02-01 04:18:58,1956,945459.0,1.0,271,6.797341e+08,False,...,1.173255e+09,56,3.0,5562.0,9506.0,NaN,NaN,http://replay271.valve.net/570/8154288597_6797...,2.036224e+18,2.446107e+18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2329,22.0,8194885179,17782,2025-02-28 21:01:35,1433,953691.0,1.0,271,1.875712e+09,False,...,2.624760e+08,57,3.0,214.0,14701.0,NaN,NaN,http://replay271.valve.net/570/8194885179_1875...,2.918651e+15,2.317470e+16
2330,22.0,8194908222,17163,2025-02-28 21:23:00,1713,953743.0,1.0,272,1.478653e+09,False,...,3.677169e+07,57,3.0,2477.0,11190.0,NaN,NaN,http://replay272.valve.net/570/8194908222_1478...,1.883095e+18,2.431454e+18
2331,22.0,8194946732,17163,2025-02-28 22:03:40,1323,953743.0,1.0,272,1.054314e+09,False,...,1.674746e+09,57,3.0,427.0,16185.0,NaN,NaN,http://replay272.valve.net/570/8194946732_1054...,2.431454e+18,1.883095e+18
2332,22.0,8194974757,17163,2025-02-28 22:36:03,2381,953743.0,1.0,272,1.617718e+09,False,...,1.202314e+08,57,3.0,5531.0,11663.0,NaN,NaN,http://replay272.valve.net/570/8194974757_1617...,1.883095e+18,2.431454e+18
2333,22.0,8195012016,17163,2025-02-28 23:29:03,1717,953764.0,1.0,273,1.545520e+09,False,...,3.158503e+08,57,3.0,0.0,12724.0,NaN,NaN,http://replay273.valve.net/570/8195012016_1545...,2.446097e+18,2.075636e+18

In [27]:
meta_df3 = pd.read_csv("main_metadata 3.csv")
meta_df3

,version,match_id,leagueid,start_date_time,duration,series_id,series_type,cluster,replay_salt,radiant_win,...,dire_captain,patch,region,comeback,stomp,throw,loss,replay_url,radiant_logo,dire_logo
0,22.0,8195037742,17163,2025-03-01 00:16:51,2159,953764.0,1.0,271,7.909613e+08,False,...,253075824.0,57,3.0,6818.0,15188.0,NaN,NaN,http://replay271.valve.net/570/8195037742_7909...,2.075636e+18,2.446097e+18
1,22.0,8195066483,17163,2025-03-01 01:07:11,1910,953764.0,1.0,272,1.328820e+09,True,...,844586465.0,57,3.0,NaN,NaN,3879.0,14439.0,http://replay272.valve.net/570/8195066483_1328...,2.446097e+18,2.075636e+18
2,22.0,8195094835,17163,2025-03-01 01:55:41,1991,953782.0,1.0,272,1.351207e+09,True,...,406522933.0,57,3.0,NaN,NaN,616.0,5998.0,http://replay272.valve.net/570/8195094835_1351...,2.041868e+18,2.504646e+18
3,22.0,8195122624,17163,2025-03-01 02:38:47,2070,953782.0,1.0,272,1.077443e+09,True,...,154357932.0,57,3.0,NaN,NaN,5125.0,7490.0,http://replay272.valve.net/570/8195122624_1077...,2.504646e+18,2.041868e+18
4,22.0,8195152293,17163,2025-03-01 03:23:27,1950,953782.0,1.0,274,4.843931e+08,False,...,406522933.0,57,3.0,8857.0,5391.0,NaN,NaN,http://replay274.valve.net/570/8195152293_4843...,2.041868e+18,2.504646e+18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399,22.0,8237266766,17874,2025-03-31 22:17:53,2858,963258.0,1.0,346,1.092553e+09,False,...,202464276.0,57,38.0,7106.0,29484.0,NaN,NaN,http://replay346.valve.net/570/8237266766_1092...,2.489997e+18,3.331605e+16
2400,22.0,8237268473,17874,2025-03-31 22:22:02,2766,963247.0,1.0,121,2.257979e+08,False,...,102446089.0,57,2.0,4061.0,25770.0,NaN,NaN,http://replay121.valve.net/570/8237268473_2257...,4.215369e+18,0.000000e+00
2401,22.0,8237294617,17211,2025-03-31 23:11:44,1718,963263.0,1.0,274,4.030843e+08,True,...,179986197.0,57,3.0,NaN,NaN,1655.0,12064.0,http://replay274.valve.net/570/8237294617_4030...,2.041868e+18,2.460727e+18
2402,22.0,8237311350,17874,2025-03-31 23:46:24,1844,963272.0,1.0,122,1.452515e+09,True,...,899041750.0,57,2.0,NaN,NaN,29.0,18621.0,http://replay122.valve.net/570/8237311350_1452...,4.215369e+18,6.259405e+16
2403,22.0,8237314421,17211,2025-03-31 23:52:38,1909,963273.0,1.0,274,1.848313e+09,False,...,95501968.0,57,3.0,5645.0,6052.0,NaN,NaN,http://replay274.valve.net/570/8237314421_1848...,1.839182e+18,2.446097e+18

In [28]:
meta_df4 = pd.read_csv("main_metadata 4.csv")
meta_df4

,version,match_id,leagueid,start_date_time,duration,series_id,series_type,cluster,replay_salt,radiant_win,...,dire_captain,patch,region,comeback,stomp,throw,loss,replay_url,radiant_logo,dire_logo
0,22.0,8237333738,17874,2025-04-01 00:34:17,1686,963272.0,1.0,122,2.007149e+09,False,...,3.191241e+08,57,2.0,7162.0,12671.0,NaN,NaN,http://replay122.valve.net/570/8237333738_2007...,6.259405e+16,4.215369e+18
1,22.0,8237333903,17211,2025-04-01 00:36:05,1804,963273.0,1.0,271,1.362944e+09,True,...,3.426673e+08,57,3.0,NaN,NaN,4262.0,9409.0,http://replay271.valve.net/570/8237333903_1362...,2.446097e+18,1.839182e+18
2,22.0,8237372778,17211,2025-04-01 01:52:32,1615,963293.0,1.0,272,8.121268e+08,True,...,1.261304e+08,57,3.0,NaN,NaN,658.0,16883.0,http://replay272.valve.net/570/8237372778_8121...,2.412313e+18,2.431454e+18
3,22.0,8237391929,17211,2025-04-01 02:28:15,2162,963293.0,1.0,271,1.798190e+08,False,...,1.673878e+09,57,3.0,6193.0,12011.0,NaN,NaN,http://replay271.valve.net/570/8237391929_1798...,2.431454e+18,2.412313e+18
4,22.0,8237577610,17874,2025-04-01 08:02:57,2497,963326.0,1.0,153,1.667491e+09,True,...,1.964000e+08,57,5.0,NaN,NaN,4076.0,17110.0,http://replay153.valve.net/570/8237577610_1667...,3.894373e+16,3.894998e+16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2506,22.0,8275298991,17211,2025-04-30 22:14:26,2092,972456.0,1.0,273,7.595763e+08,True,...,1.234067e+08,57,3.0,NaN,NaN,4673.0,7968.0,http://replay273.valve.net/570/8275298991_7595...,2.047503e+18,2.460727e+18
2507,22.0,8275325420,17367,2025-04-30 22:52:27,1908,972451.0,2.0,381,5.325388e+08,False,...,1.868375e+08,57,NaN,-847.0,29348.0,NaN,NaN,http://replay381.valve.net/570/8275325420_5325...,4.045900e+15,5.358858e+16
2508,22.0,8275328415,17211,2025-04-30 22:58:26,1734,972456.0,1.0,273,1.300096e+09,False,...,8.453443e+08,57,3.0,537.0,16786.0,NaN,NaN,http://replay273.valve.net/570/8275328415_1300...,2.460727e+18,2.047503e+18
2509,22.0,8275350779,17211,2025-04-30 23:39:43,1581,972463.0,1.0,273,8.133797e+08,True,...,3.512789e+07,57,3.0,NaN,NaN,4706.0,9806.0,http://replay273.valve.net/570/8275350779_8133...,2.504646e+18,1.990058e+18
2510,22.0,8275351883,17367,2025-04-30 23:50:50,2357,972451.0,2.0,381,8.393544e+08,True,...,1.807750e+08,57,NaN,NaN,NaN,411.0,21088.0,http://replay381.valve.net/570/8275351883_8393...,5.358858e+16,4.045900e+15

In [32]:
meta_df5 = pd.read_csv("main_metadata 5.csv")
meta_df5

,version,match_id,leagueid,start_date_time,duration,series_id,series_type,cluster,replay_salt,radiant_win,...,dire_captain,patch,region,comeback,stomp,throw,loss,replay_url,radiant_logo,dire_logo
0,22.0,8275370918,17211,2025-05-01 00:18:25,2213,972463.0,1.0,274,1.360983e+09,False,...,2.501445e+08,57,3.0,6059.0,6086.0,NaN,NaN,http://replay274.valve.net/570/8275370918_1360...,1.990058e+18,2.504646e+18
1,22.0,8275394943,17367,2025-05-01 01:02:40,2209,972451.0,2.0,251,1.044067e+09,True,...,1.807750e+08,57,15.0,NaN,NaN,16836.0,6071.0,http://replay251.valve.net/570/8275394943_1044...,5.358858e+16,4.045900e+15
2,22.0,8275398663,17211,2025-05-01 01:10:39,1592,972486.0,1.0,274,4.278766e+07,False,...,2.530758e+08,57,3.0,3602.0,16870.0,NaN,NaN,http://replay274.valve.net/570/8275398663_4278...,1.908989e+18,2.446097e+18
3,22.0,8275420119,17211,2025-05-01 01:50:00,2077,972486.0,1.0,274,7.067411e+08,True,...,2.362360e+08,57,3.0,NaN,NaN,78.0,15815.0,http://replay274.valve.net/570/8275420119_7067...,2.446097e+18,1.908989e+18
4,22.0,8275465914,18105,2025-05-01 03:05:41,1699,972506.0,1.0,151,5.401623e+08,True,...,1.766163e+08,57,5.0,NaN,NaN,0.0,22833.0,http://replay151.valve.net/570/8275465914_5401...,3.782290e+16,2.027237e+18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266,22.0,8298974061,17211,2025-05-19 01:30:59,1804,977343.0,1.0,271,1.522760e+09,True,...,1.773383e+08,57,3.0,NaN,NaN,6.0,22878.0,http://replay271.valve.net/570/8298974061_1522...,2.504646e+18,1.908989e+18
1267,22.0,8298995380,17211,2025-05-19 02:12:33,1836,977343.0,1.0,272,1.803537e+09,False,...,1.922760e+08,57,3.0,1358.0,16474.0,NaN,NaN,http://replay272.valve.net/570/8298995380_1803...,1.908989e+18,2.504646e+18
1268,22.0,8299053408,16325,2025-05-19 04:03:11,1552,977383.0,1.0,274,6.151853e+08,False,...,1.525058e+09,57,3.0,0.0,11666.0,NaN,NaN,http://replay274.valve.net/570/8299053408_6151...,2.443837e+18,2.068882e+18
1269,22.0,8299054363,17233,2025-05-19 04:02:37,1520,977384.0,1.0,274,2.084663e+09,False,...,1.749631e+09,57,3.0,3586.0,9377.0,NaN,NaN,http://replay274.valve.net/570/8299054363_2084...,1.403379e+19,1.495768e+19
1270,22.0,8299073970,16325,2025-05-19 04:38:32,1861,977383.0,1.0,271,1.857330e+09,True,...,1.669908e+09,57,3.0,NaN,NaN,4331.0,14528.0,http://replay271.valve.net/570/8299073970_1857...,2.068882e+18,2.443837e+18

In [40]:
import pandas as pd

# Список всех датафреймов (ключевой + дополнительные)
all_dfs = [meta_df, meta_df1, meta_df2, meta_df3, meta_df4, meta_df5]  # Добавьте все ваши датасеты

# Объединяем все датафреймы вертикально
combined_df = pd.concat(all_dfs)

In [41]:
print(f"Исходный размер meta_df: {meta_df.shape}")
print(f"Размер combined_df после объединения: {combined_df.shape}")
print(combined_df.head())

Исходный размер meta_df: (30012, 13)
Размер combined_df после объединения: (41498, 49)
     match_id  duration radiant_win  dire_hero_1  dire_hero_2  dire_hero_3  \
0  7515635423      1926        True         71.0         26.0         87.0
1  7515660161      1731       False         95.0        107.0        123.0
2  7515737711      2056        True        137.0        112.0        103.0
3  7515745579      2221        True         27.0        100.0         33.0
4  7515769503      1998       False        102.0        121.0         85.0

   dire_hero_4  dire_hero_5  radiant_hero_1  radiant_hero_2  ...  \
0         48.0         39.0            83.0            79.0  ...
1         68.0         17.0           119.0            50.0  ...
2         16.0         35.0            27.0            98.0  ...
3         25.0         76.0             5.0            26.0  ...
4         10.0         39.0            71.0            30.0  ...

   dire_captain  patch  region  throw  loss comeback  stomp  replay_url  \
0           NaN    NaN     NaN    NaN   NaN      NaN    NaN         NaN
1           NaN    NaN     NaN    NaN   NaN      NaN    NaN         NaN
2           NaN    NaN     NaN    NaN   NaN      NaN    NaN         NaN
3           NaN    NaN     NaN    NaN   NaN      NaN    NaN         NaN
4           NaN    NaN     NaN    NaN   NaN      NaN    NaN         NaN

   series_id  series_type
0        NaN          NaN
1        NaN          NaN
2        NaN          NaN
3        NaN          NaN
4        NaN          NaN

[5 rows x 49 columns]

In [42]:
combined_df

,match_id,duration,radiant_win,dire_hero_1,dire_hero_2,dire_hero_3,dire_hero_4,dire_hero_5,radiant_hero_1,radiant_hero_2,...,dire_captain,patch,region,throw,loss,comeback,stomp,replay_url,series_id,series_type
0,7515635423,1926,True,71.0,26.0,87.0,48.0,39.0,83.0,79.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7515660161,1731,False,95.0,107.0,123.0,68.0,17.0,119.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7515737711,2056,True,137.0,112.0,103.0,16.0,35.0,27.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7515745579,2221,True,27.0,100.0,33.0,25.0,76.0,5.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7515769503,1998,False,102.0,121.0,85.0,10.0,39.0,71.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266,8298974061,1804,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.773383e+08,57.0,3.0,6.0,22878.0,NaN,NaN,http://replay271.valve.net/570/8298974061_1522...,977343.0,1.0
1267,8298995380,1836,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.922760e+08,57.0,3.0,NaN,NaN,1358.0,16474.0,http://replay272.valve.net/570/8298995380_1803...,977343.0,1.0
1268,8299053408,1552,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.525058e+09,57.0,3.0,NaN,NaN,0.0,11666.0,http://replay274.valve.net/570/8299053408_6151...,977383.0,1.0
1269,8299054363,1520,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.749631e+09,57.0,3.0,NaN,NaN,3586.0,9377.0,http://replay274.valve.net/570/8299054363_2084...,977384.0,1.0
1270,8299073970,1861,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.669908e+09,57.0,3.0,4331.0,14528.0,NaN,NaN,http://replay271.valve.net/570/8299073970_1857...,977383.0,1.0

In [44]:
filter_matches(combined_df,[83.0], [71.0])

,match_id,duration,radiant_win,dire_hero_1,dire_hero_2,dire_hero_3,dire_hero_4,dire_hero_5,radiant_hero_1,radiant_hero_2,...,dire_captain,patch,region,throw,loss,comeback,stomp,replay_url,series_id,series_type
0,7515635423,1926,True,71.0,26.0,87.0,48.0,39.0,83.0,79.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7518788908,2038,False,88.0,123.0,71.0,80.0,54.0,83.0,19.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7520192386,1981,True,61.0,83.0,38.0,119.0,57.0,53.0,55.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7522276083,2480,True,71.0,53.0,86.0,48.0,47.0,102.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7525887594,2540,False,83.0,123.0,14.0,10.0,62.0,53.0,71.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,8004809604,2020,False,84.0,72.0,71.0,126.0,76.0,88.0,112.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,8049575247,1811,True,83.0,123.0,109.0,104.0,39.0,11.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,8059341092,1614,False,71.0,26.0,27.0,74.0,46.0,83.0,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,8066949195,1528,False,14.0,120.0,100.0,71.0,73.0,11.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,8084413930,1594,False,83.0,123.0,49.0,46.0,35.0,71.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
print(combined_df.columns)

Index(['match_id', 'duration', 'radiant_win', 'dire_hero_1', 'dire_hero_2',
       'dire_hero_3', 'dire_hero_4', 'dire_hero_5', 'radiant_hero_1',
       'radiant_hero_2', 'radiant_hero_3', 'radiant_hero_4', 'radiant_hero_5',
       'version', 'leagueid', 'start_date_time', 'cluster', 'replay_salt',
       'pre_game_duration', 'match_seq_num', 'tower_status_radiant',
       'tower_status_dire', 'barracks_status_radiant', 'barracks_status_dire',
       'first_blood_time', 'lobby_type', 'human_players', 'game_mode', 'flags',
       'engine', 'radiant_score', 'dire_score', 'radiant_team_id',
       'radiant_logo', 'radiant_team_complete', 'dire_team_id', 'dire_logo',
       'dire_team_complete', 'radiant_captain', 'dire_captain', 'patch',
       'region', 'throw', 'loss', 'comeback', 'stomp', 'replay_url',
       'series_id', 'series_type'],
      dtype='object')

In [56]:
combined_df = combined_df.drop(columns=["region", "throw", "loss", "comeback", "stomp", "replay_url","series_id", "series_type"])
combined_df

,match_id,duration,radiant_win,dire_hero_1,dire_hero_2,dire_hero_3,dire_hero_4,dire_hero_5,radiant_hero_1,radiant_hero_2,...,dire_score,radiant_team_id,radiant_logo,radiant_team_complete,dire_team_id,dire_logo,dire_team_complete,radiant_captain,dire_captain,patch
0,7515635423,1926,True,71.0,26.0,87.0,48.0,39.0,83.0,79.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7515660161,1731,False,95.0,107.0,123.0,68.0,17.0,119.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7515737711,2056,True,137.0,112.0,103.0,16.0,35.0,27.0,98.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7515745579,2221,True,27.0,100.0,33.0,25.0,76.0,5.0,26.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7515769503,1998,False,102.0,121.0,85.0,10.0,39.0,71.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266,8298974061,1804,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.0,8849850.0,2.504646e+18,1.0,8850100.0,1.908989e+18,1.0,4.065229e+08,1.773383e+08,57.0
1267,8298995380,1836,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,41.0,8850100.0,1.908989e+18,1.0,8849850.0,2.504646e+18,1.0,8.392190e+08,1.922760e+08,57.0
1268,8299053408,1552,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.0,9332046.0,2.443837e+18,1.0,9018528.0,2.068882e+18,0.0,1.669908e+09,1.525058e+09,57.0
1269,8299054363,1520,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.0,8629014.0,1.403379e+19,1.0,9767998.0,1.495768e+19,1.0,9.486598e+08,1.749631e+09,57.0
1270,8299073970,1861,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.0,9018528.0,2.068882e+18,0.0,9332046.0,2.443837e+18,1.0,1.524969e+09,1.669908e+09,57.0

In [58]:
print(combined_df.columns)

Index(['match_id', 'duration', 'radiant_win', 'dire_hero_1', 'dire_hero_2',
       'dire_hero_3', 'dire_hero_4', 'dire_hero_5', 'radiant_hero_1',
       'radiant_hero_2', 'radiant_hero_3', 'radiant_hero_4', 'radiant_hero_5',
       'version', 'leagueid', 'start_date_time', 'cluster', 'replay_salt',
       'pre_game_duration', 'match_seq_num', 'tower_status_radiant',
       'tower_status_dire', 'barracks_status_radiant', 'barracks_status_dire',
       'first_blood_time', 'lobby_type', 'human_players', 'game_mode', 'flags',
       'engine', 'radiant_score', 'dire_score', 'radiant_team_id',
       'radiant_logo', 'radiant_team_complete', 'dire_team_id', 'dire_logo',
       'dire_team_complete', 'radiant_captain', 'dire_captain', 'patch'],
      dtype='object')

In [66]:
import pandas as pd
from collections import defaultdict

def precompute_hero_statistics(df):
    """Предварительно вычисляет статистику героев: синергии, контрпики и винрейты."""
   
    required_columns = [f'{team}_hero_{i}' for team in ['radiant', 'dire'] for i in range(1, 6)]
    required_columns.append('radiant_win')
    
    missing_cols = [col for col in required_columns if col not in df.columns]
    if missing_cols:
        raise ValueError(f"В данных отсутствуют обязательные колонки: {missing_cols}")

    hero_pairs_synergy = defaultdict(lambda: defaultdict(lambda: [0, 0]))  # [wins, total]
    hero_pairs_counter = defaultdict(lambda: defaultdict(lambda: [0, 0]))
    hero_win_rates = defaultdict(lambda: [0, 0])  # [wins, total]
    
    all_heroes = set()
    for i in range(1, 6):
        all_heroes.update(df[f'radiant_hero_{i}'].dropna().unique())
        all_heroes.update(df[f'dire_hero_{i}'].dropna().unique())
    
 
    for _, row in df.iterrows():
        radiant_heroes = [row[f'radiant_hero_{i}'] for i in range(1, 6) if not pd.isna(row[f'radiant_hero_{i}'])]
        dire_heroes = [row[f'dire_hero_{i}'] for i in range(1, 6) if not pd.isna(row[f'dire_hero_{i}'])]
        radiant_win = row['radiant_win']
        
        for hero in radiant_heroes:
            hero_win_rates[hero][1] += 1
            hero_win_rates[hero][0] += 1 if radiant_win else 0
        for hero in dire_heroes:
            hero_win_rates[hero][1] += 1
            hero_win_rates[hero][0] += 0 if radiant_win else 1
        

        for team in [radiant_heroes, dire_heroes]:
            for i in range(len(team)):
                for j in range(i + 1, len(team)):
                    h1, h2 = team[i], team[j]
                    hero_pairs_synergy[h1][h2][1] += 1
                    hero_pairs_synergy[h2][h1][1] += 1
                    if (team is radiant_heroes and radiant_win) or (team is dire_heroes and not radiant_win):
                        hero_pairs_synergy[h1][h2][0] += 1
                        hero_pairs_synergy[h2][h1][0] += 1
        
        for r_hero in radiant_heroes:
            for d_hero in dire_heroes:
                hero_pairs_counter[r_hero][d_hero][1] += 1
                hero_pairs_counter[d_hero][r_hero][1] += 1
                if radiant_win:
                    hero_pairs_counter[r_hero][d_hero][0] += 1
                else:
                    hero_pairs_counter[d_hero][r_hero][0] += 1
  
    synergy_rates = {}
    for h1, partners in hero_pairs_synergy.items():
        synergy_rates[h1] = {}
        for h2, (wins, total) in partners.items():
            synergy_rates[h1][h2] = wins / total if total > 0 else 0.5
    
    counter_rates = {}
    for h1, opponents in hero_pairs_counter.items():
        counter_rates[h1] = {}
        for h2, (wins, total) in opponents.items():
            counter_rates[h1][h2] = wins / total if total > 0 else 0.5
    
    win_rates = {hero: wins / total for hero, (wins, total) in hero_win_rates.items()}
    
    return {
        'synergy_rates': synergy_rates,
        'counter_rates': counter_rates,
        'win_rates': win_rates,
        'all_heroes': list(all_heroes)
    }

def get_hero_recommendations(
    player_side,          
    team_heroes,         
    enemy_heroes,         
    banned_heroes,        
    stats,               
    preferred_heroes=[],  
    n_picks=5,          
    n_bans=5,            
    synergy_weight=0.4,   
    counter_weight=0.4,   
    win_rate_weight=0.2  
):
    """Рекомендует героев для пика и бана на основе статистики матчей."""
    available_heroes = [
        h for h in stats['all_heroes'] 
        if h not in banned_heroes + team_heroes + enemy_heroes
    ]
    pick_scores = []
    for hero in available_heroes:
        synergy_score = 0
        if team_heroes:
            for teammate in team_heroes:
                if teammate in stats['synergy_rates'].get(hero, {}):
                    synergy_score += stats['synergy_rates'][hero][teammate]
            synergy_score /= len(team_heroes) if team_heroes else 1
        counter_score = 0
        if enemy_heroes:
            for enemy in enemy_heroes:
                if enemy in stats['counter_rates'].get(hero, {}):
                    counter_score += stats['counter_rates'][hero][enemy]
            counter_score /= len(enemy_heroes) if enemy_heroes else 1
        win_score = stats['win_rates'].get(hero, 0.5)
        preference_bonus = 0.1 if hero in preferred_heroes else 0
        total_score = (
            synergy_weight * synergy_score +
            counter_weight * counter_score +
            win_rate_weight * win_score +
            preference_bonus
        )
        pick_scores.append((hero, total_score))
    pick_scores.sort(key=lambda x: x[1], reverse=True)
    recommended_picks = [hero for hero, score in pick_scores[:n_picks]]
    ban_candidates = [h for h in stats['all_heroes'] if h not in banned_heroes]
    ban_scores = []
    
    for hero in ban_candidates:
        danger_score = 0
        if team_heroes:
            for teammate in team_heroes:
                if hero in stats['counter_rates'].get(teammate, {}):
                    danger_score += 1 - stats['counter_rates'][teammate][hero]  
            danger_score /= len(team_heroes) if team_heroes else 1
        win_score = stats['win_rates'].get(hero, 0.5)
        
        ban_scores.append((hero, danger_score * 0.7 + win_score * 0.3))
    
    ban_scores.sort(key=lambda x: x[1], reverse=True)
    recommended_bans = [hero for hero, score in ban_scores[:n_bans]]
    
    return {
        'recommended_picks': recommended_picks,
        'recommended_bans': recommended_bans,
        'pick_scores': pick_scores[:n_picks],
        'ban_scores': ban_scores[:n_bans]
    }

if __name__ == "__main__":
    try:
        df = combined_df  

        print("Вычисление статистики героев...")
        stats = precompute_hero_statistics(df)
        print("Статистика успешно вычислена!")
        
        print("\nГенерация рекомендаций...")
        recommendations = get_hero_recommendations(
            player_side='radiant',
            team_heroes=[11, 32],    # Shadow Fiend и Jakiro
            enemy_heroes=[45, 23],    #Pudge и Phantom Assassin
            banned_heroes=[18, 53],   # Invoker и Anti-Mage
            stats=stats,
            preferred_heroes=[74, 20] #Templar Assassin и Brewmaster
        )
        
        print("\nТоп рекомендуемых пиков:")
        for i, (hero, score) in enumerate(recommendations['pick_scores'], 1):
            print(f"{i}. Герой {hero}: {score:.2%}")
            
        print("\nТоп рекомендуемых банов:")
        for i, (hero, score) in enumerate(recommendations['ban_scores'], 1):
            print(f"{i}. Герой {hero}: {score:.2%}")
            
    except Exception as e:
        print(f"Ошибка: {str(e)}")

Вычисление статистики героев...
Статистика успешно вычислена!

Генерация рекомендаций...

Топ рекомендуемых пиков:
1. Герой 20.0: 61.02%
2. Герой 89.0: 60.49%
3. Герой 42.0: 60.23%
4. Герой 74.0: 60.13%
5. Герой 137.0: 59.75%

Топ рекомендуемых банов:
1. Герой 66.0: 76.97%
2. Герой 43.0: 70.28%
3. Герой 47.0: 68.86%
4. Герой 61.0: 67.59%
5. Герой 62.0: 66.21%